"use client";

import Image from "next/image";
import { useState, useRef, useEffect } from "react";
import { Play, Pause, SkipForward } from "lucide-react";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/app/components/ui/tooltip";

// Based off 3kh0's music player https://github.com/3kh0/simple-music-player
// Playlist is generated by scrape.py -> public/music/songs.json

type Song = {
  title: string;
  src: string;
  cover: string | null;
  link: string;
};

export default function MusicPlayer() {
  const [songs, setSongs] = useState<Song[]>([]);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentSongIndex, setCurrentSongIndex] = useState(0);
  const [isInitialized, setIsInitialized] = useState(false);
  const audioRef = useRef<HTMLAudioElement>(null);
  const endTimeRef = useRef<number | null>(null);

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.volume = 0.1;
    }
  }, []);

  useEffect(() => {
    fetch("/music/songs.json")
      .then((r) => r.json())
      .then((j: Song[]) => {
        if (!Array.isArray(j) || !j.length) return;
        setSongs(j);
        setCurrentSongIndex(Math.floor(Math.random() * j.length));
      })
      .catch((e) => console.error("Playlist load failed:", e));
  }, []);

  useEffect(() => {
    if (isInitialized && audioRef.current && songs.length) {
      endTimeRef.current = null;
      audioRef.current.src = `/music/${songs[currentSongIndex].src}`;
      audioRef.current.load();
      if (isPlaying) {
        audioRef.current
          .play()
          .catch((e) => console.error("Playback failed:", e));
      }
    }
  }, [currentSongIndex, isInitialized, songs, isPlaying]);

  useEffect(() => {
    if (isInitialized && audioRef.current) {
      if (isPlaying) {
        audioRef.current
          .play()
          .catch((e) => console.error("Playback failed:", e));
      } else {
        audioRef.current.pause();
      }
    }
  }, [isPlaying, isInitialized]);

  const togglePlay = () => {
    if (!songs.length) return;
    if (!isInitialized) {
      setIsInitialized(true);
      setIsPlaying(true);
    } else {
      setIsPlaying(!isPlaying);
    }
  };

  const skipSong = () => {
    if (!songs.length) return;
    setCurrentSongIndex(Math.floor(Math.random() * songs.length));
    if (!isInitialized) setIsInitialized(true);
    setIsPlaying(true);
  };

  const handleLoadedMetadata = () => {
    if (audioRef.current) {
      const duration = audioRef.current.duration;
      if (duration > 60) {
        const randomStart = Math.floor(Math.random() * (duration - 60));
        audioRef.current.currentTime = randomStart;
        endTimeRef.current = randomStart + 60;
      } else {
        audioRef.current.currentTime = 0;
        endTimeRef.current = duration;
      }
      audioRef.current.volume = 0;
      const fadeIn = setInterval(() => {
        if (audioRef.current && audioRef.current.volume < 0.1) {
          audioRef.current.volume = Math.min(
            0.1,
            audioRef.current.volume + 0.01,
          );
        } else {
          clearInterval(fadeIn);
        }
      }, 200);
    }
  };

  const handleTimeUpdate = () => {
    if (audioRef.current && endTimeRef.current !== null) {
      const timeLeft = endTimeRef.current - audioRef.current.currentTime;
      if (timeLeft <= 2 && timeLeft > 0) {
        if (audioRef.current.volume > 0) {
          audioRef.current.volume = Math.max(0, audioRef.current.volume - 0.01);
        }
      }
      if (audioRef.current.currentTime >= endTimeRef.current) {
        endTimeRef.current = null;
        skipSong();
      }
    }
  };

  const currentSong = songs[currentSongIndex];

  return (
    <div
      id="music-box"
      className="fixed bottom-0 right-0 w-auto max-w-[calc(100vw-20px)] bg-[#121b20]/92 border border-white/15 backdrop-blur-md flex justify-between items-center p-2.5 m-2.5 rounded-[10px] z-10"
    >
      {isPlaying && currentSong && (
        <Image
          id="music-cover"
          src={
            currentSong.cover ??
            `/img/${currentSong.src.replace("music", "cover").replace(".mp3", ".png")}`
          }
          alt="Cover Art"
          width={32}
          height={32}
          className="w-8 h-8 rounded-[5px] mr-2.5 block"
        />
      )}
      <div className="flex flex-col grow min-w-0 text-left justify-center">
        <p
          id="music-info"
          className="text-base text-white m-0 p-0 leading-tight truncate"
        >
          {isPlaying && currentSong ? (
            <a
              href={currentSong.link}
              target="_blank"
              rel="noopener noreferrer"
              className="hover:underline"
            >
              {currentSong.title}
            </a>
          ) : (
            ""
          )}
        </p>
        {isPlaying && currentSong?.title.includes("25mxfu") && (
          <a
            href="https://25mxfu.bandcamp.com/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[10px] text-slate-100/90 hover:text-white m-0 p-0 leading-tight transition-colors"
          >
            support my friend&apos;s music
          </a>
        )}
      </div>
      <Tooltip>
        <TooltipTrigger asChild>
          <button
            id="music"
            className="flex items-center justify-center w-8 h-8 border-none cursor-pointer rounded-full ml-0 hover:bg-gray-700 transition-colors shrink-0"
            onClick={togglePlay}
            aria-label="Play or pause music"
          >
            {isPlaying ? (
              <Pause className="w-5 h-5 text-white" />
            ) : (
              <Play className="w-5 h-5 text-white" />
            )}
          </button>
        </TooltipTrigger>
        <TooltipContent>{isPlaying ? "Pause" : "Play"}</TooltipContent>
      </Tooltip>
      <Tooltip>
        <TooltipTrigger asChild>
          <button
            id="music-skip"
            className={`flex items-center justify-center w-8 h-8 border-none cursor-pointer rounded-full hover:bg-gray-700 transition-colors shrink-0 ${
              isPlaying ? "block" : "hidden"
            }`}
            onClick={skipSong}
            aria-label="Skip current song"
          >
            <SkipForward className="w-5 h-5 text-white" />
          </button>
        </TooltipTrigger>
        <TooltipContent>Skip</TooltipContent>
      </Tooltip>
      <audio
        ref={audioRef}
        id="music-src"
        hidden
        onEnded={skipSong}
        onLoadedMetadata={handleLoadedMetadata}
        onTimeUpdate={handleTimeUpdate}
      ></audio>
    </div>
  );
}